%% Figures for the paper
function [] = figuresForPaper()

%------------------------------
%% BASELINE FIGURES
%------------------------------
load(['Mat files' filesep 'resultBaseline.mat']);

%% Firm size distribution
firmSize     = sum(qualityFirmA,2);
firmSize     = reshape(firmSize,size(firmSize,1),size(firmSize,3));
firmSize     = firmSize(:,1);

fig1 = figure();
histogram(firmSize,'Normalization','probability');

hXLabel = xlabel('Firm Size (Normalized)'      );
hYLabel = ylabel('Probability'  );

xlim([0.0,10])
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 10          );

set(gca, ...
  'Box'         , 'on'     , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'      , ...
  'YGrid'       , 'off'      , ...
  'XGrid'       , 'off'      , ...
  'XColor'      , [.0 .0 .0], ...
  'YColor'      , [.0 .0 .0], ...
  'LineWidth'   , 0.5         );

print(fig1,'-dpdf','-bestfit',['Figures' filesep 'firmSizeDist.pdf']);
close all
% -------------------------------------------------------------------

%% Product line distribution
nProduct     = nProdA(:,1);

fig2 = figure();
histogram(nProduct,'Normalization','probability');

hXLabel = xlabel('Number of Product Lines'              );
hYLabel = ylabel('Probability'  );

xlim([0.0,10])


set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 14          );


set(gca, ...
  'Box'         , 'on'     , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'      , ...
  'YGrid'       , 'off'      , ...
  'XGrid'       , 'off'      , ...
  'XColor'      , [.0 .0 .0], ...
  'YColor'      , [.0 .0 .0], ...
  'LineWidth'   , 1.5         );

set(gcf, 'PaperPositionMode', 'auto');
print(fig2,'-dpdf',['Figures' filesep 'productDist.pdf'])

close all
% -------------------------------------------------------------------

%% Firm Size vs Number of Product lines
line45 = 0:1:13;
fig3 = figure();
scatter(nProduct,firmSize)
hold on
plot(line45,line45,'k','LineWidth',2)


hXLabel = xlabel('Number of Product Lines');
hYLabel = ylabel('Firm Size (Normalized)'  );

xlim([0.0,13])
ylim([0.0,13])


set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 14          );


set(gca, ...
  'Box'         , 'on'     , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'      , ...
  'YGrid'       , 'off'      , ...
  'XGrid'       , 'off'      , ...
  'XColor'      , [.0 .0 .0], ...
  'YColor'      , [.0 .0 .0], ...
  'LineWidth'   , 1.5         );

set(gcf, 'PaperPositionMode', 'auto');
print(fig3,'-dpdf',['Figures' filesep 'firmSizeVSproductLine.pdf'])
close all
% -------------------------------------------------------------------

%% Citation Distribution

a = csvread('citeDistribution.csv',1,0);
probExternal85_94  = a(:,2);
pointExternal85_94 = a(:,1);

probExternal85_94(isnan(probExternal85_94))     = [];
pointExternal85_94(isnan(pointExternal85_94))   = [];

begin  = 1;
ending = 31;

probExternal85_94  = probExternal85_94((begin):ending+begin-1);
probExternal85_94  = probExternal85_94/sum(probExternal85_94);
pointExternal85_94 = pointExternal85_94((begin):ending+begin-1);

[fn] = citDistModel(p.theta,p.gammaeta,p.alpha,begin);

fig4 = figure();
model = plot(((begin-1):(length(fn) + begin-2)),fn);
hold on
data  = plot(pointExternal85_94(1:ending),probExternal85_94(1:ending));

hLegend = legend('Model','Data');


hXLabel = xlabel('Number of Citations Received');
hYLabel = ylabel('Probability');

xlim([0.0,30])

set(model                        , ...
  'LineStyle'       , '-'          , ...
  'LineWidth'       , 3             );

set(data                        , ...
  'LineStyle'       , '--'          , ...
  'Color'           , [.9 .3 .3]    , ...
  'LineWidth'       , 3             );

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hLegend, gca]             , ...
    'FontSize'   , 12           );
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 14          );

set(gca, ...
  'Box'         , 'on'     , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'      , ...
  'YGrid'       , 'off'      , ...
  'XGrid'       , 'off'      , ...
  'XColor'      , [.0 .0 .0], ...
  'YColor'      , [.0 .0 .0], ...
  'LineWidth'   , 1.5         );

set(gcf, 'PaperPositionMode', 'auto');
print(fig4,'-dpdf',['Figures' filesep 'citeDist.pdf'])
close all
clear all
% -------------------------------------------------------------------

%% Value Function and Innovation for different sigma values
load(['Mat files' filesep 'resultBaselineVarySigma.mat']);
% Add sigma = 0 case: Bn = 0 because of fixed cost
Bn = [zeros(1,size(Bn,2));Bn];
Bn(:,1) = 0;

fig5 = figure();
% Value Function
bn = plot(0:1:length(Bn)-1,Bn);

hLegend = legend('\sigma=0 (Baseline)','\sigma=0.2','\sigma=0.4','\sigma=0.5 (KK)','Location','NorthWest');

hXLabel = xlabel('Number of Product Lines');
hYLabel = ylabel('B_{n}'  );

xlim([0.0,10])
ylim([-0.5,3])

set(bn(2)                        , ...
  'LineStyle'       , '--'          , ...
  'Color'           , bn(1).Color - [0 .15 .15], ...
  'LineWidth'       , 3             );
set(bn(3)                        , ...
  'LineStyle'       , '-.'          , ...
  'Color'           , bn(1).Color   , ...
  'LineWidth'       , 3             );
set(bn(4)                        , ...
  'LineStyle'       , '-'          , ...
  'Color'           , bn(1).Color  + [0 .1 .1]  , ...
  'LineWidth'       , 3             );
set(bn(1)                        , ...
  'LineStyle'       , '-'          , ...
  'Color'           , bn(1).Color - [0 .30 .30]    , ...
  'LineWidth'       , 3             );

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hLegend, gca]             , ...
    'FontSize'   , 12          );
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 14          );


set(gca, ...
  'Box'         , 'on'     , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'      , ...
  'YGrid'       , 'off'      , ...
  'XGrid'       , 'off'      , ...
  'XColor'      , [.0 .0 .0], ...
  'YColor'      , [.0 .0 .0], ...
  'LineWidth'   , 1.5         );

set(gcf, 'PaperPositionMode', 'auto');
print(fig5,'-dpdf',['Figures' filesep 'Bn.pdf'])
close all
clear all

% -------------------------------------------------------------------
fig6 = figure();
% Innovation incentives
load(['Mat files' filesep 'resultBaseline.mat']);
load(['Mat files' filesep 'resultBaselineVarySigma.mat']);

xn = plot(innovation);   


hLegend = legend('\sigma=0 (Baseline)','\sigma=0.2','\sigma=0.4','\sigma=0.5 (KK)','Location','NorthEast');
hXLabel = xlabel('Number of Product Lines (n)');
hYLabel = ylabel('x_{n}');

xlim([0.5,20])
ylim([0.0,.13])

set(xn(2)                        , ...
  'LineStyle'       , '--'          , ...
  'Color'           , xn(1).Color - [0 .15 .15], ...
  'LineWidth'       , 3             );
set(xn(3)                        , ...
  'LineStyle'       , '-.'          , ...
  'Color'           , xn(1).Color   , ...
  'LineWidth'       , 3             );
set(xn(4)                        , ...
  'LineStyle'       , '-'          , ...
  'Color'           , xn(1).Color  + [0 .1 .1]  , ...
  'LineWidth'       , 3             );
set(xn(1)                        , ...
  'LineStyle'       , '-'          , ...
  'Color'           , xn(1).Color - [0 .30 .30]    , ...
  'LineWidth'       , 3             );

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hLegend, gca]             , ...
    'FontSize'   , 12          );
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 14          );


set(gca, ...
  'Box'         , 'on'     , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'      , ...
  'YGrid'       , 'off'      , ...
  'XGrid'       , 'off'      , ...
  'XColor'      , [.0 .0 .0], ...
  'YColor'      , [.0 .0 .0], ...
  'LineWidth'   , 1.5         );

set(gcf, 'PaperPositionMode', 'auto');
print(fig6,'-dpdf',['Figures' filesep 'xn.pdf'])
close all
clear all
% -------------------------------------------------------------------

%% Cost Multiplier for Major Innovation 
load(['Mat files' filesep 'resultBaseline.mat']);

state = 1:10;
n_ = (state.^((1 - p.sigma)*p.psiTilde))./state;

fig2 = figure();
a = plot(n_,'LineWidth',3);

hXLabel = xlabel({'Firm Size';'(Number of Product Lines)'});
hYLabel = ylabel({'Cost of Innovation'; '(Rel to 1-Product Firm)'}  );

xlim([.5,10.5])
ylim([.95,1.65])

 set(a                        , ...
     'MarkerSize'      , 9             , ...
   'Marker'          , 'o'           );

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 15          );

set(gca, ...
  'Box'         , 'on'     , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'      , ...
  'YGrid'       , 'off'      , ...
  'XGrid'       , 'off'      , ...
  'XColor'      , [.0 .0 .0], ...
  'YColor'      , [.0 .0 .0], ...
  'LineWidth'   , 1.5         );

set(gcf, 'PaperPositionMode', 'auto');
set(gca,'FontSize',15)
print(fig2,'-dpdf',['Figures' filesep 'costOfInnovation.pdf'])
close all
% -------------------------------------------------------------------

%% Share of Major Advances in Firm’s Innovation Portfolio

state = 1:10;
n_ = (state'.*eq.xn(1:10)*p.theta)./(eq.xn(1:10).*state' + eq.z*state');

fig2 = figure();
a = plot(n_,'LineWidth',3);

hXLabel = xlabel({'Firm Size';'(Number of Product Lines)'}              );
hYLabel = ylabel({''}  );

xlim([.5,10.5])
%ylim([.95,1.65])

 set(a                        , ...
     'MarkerSize'      , 9             , ...
   'Marker'          , 'o'           );

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 15          );


set(gca, ...
  'Box'         , 'on'     , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'      , ...
  'YGrid'       , 'off'      , ...
  'XGrid'       , 'off'      , ...
  'XColor'      , [.0 .0 .0], ...
  'YColor'      , [.0 .0 .0], ...
  'LineWidth'   , 1.5         );

set(gcf, 'PaperPositionMode', 'auto');
set(gca,'FontSize',15)
print(fig2,'-dpdf',['Figures' filesep 'shareRadicalInno.pdf'])

close all

end


% end

