%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Filename: robustness_code.m
% Author: Craig A. Chikis
% Date: 10/15/2022
% Note(s):
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [] = robustness_code() 

    models = {@inelastic_labor, @gamma66_current, @eta6p_param, @rho015_param, ...
                @varphi250_current, @varphi500_current, ...
                @gamma33_current, @eta3p_param, @kappa12_param, @kappa24_param, @kappa36_param, ...
                @highmarkup_param, @entry_current, @entry_current_directed, ...
                @no_nqtr_profit_param, @benchmark_current_fric, @no_pos_RD_param, ...
                @oi_03p, @oi_3p};
                
    m = models{1}(); 

    rho_vec = sort([power(1 + linspace(1e-3, 0.05, 25), 1/12) - 1, m.rho]);
            
    gveccollect = nan(length(models), length(rho_vec));
    markup_p50_collect = nan(size(gveccollect));
    markup_p90_collect = nan(size(gveccollect));
    markup_mean_collect = nan(size(gveccollect)); 

    run_these = 1:length(models); 

    m_collect = cell(1, length(run_these)); 
    for (ii = run_these)
        m = models{ii}();
        
        m = workhorse_nested_robust(m); 
        
        gveciter = nan(size(rho_vec));
        markup_p50_iter = nan(size(rho_vec));
        markup_p90_iter = nan(size(rho_vec)); 
        markup_mean_iter = nan(size(rho_vec));
        m_vec_iter = cell(1, length(rho_vec));
        for (jj = 1:length(rho_vec))
            m_iter = m; 
            m_iter.rho = rho_vec(jj); 
            m_vec_iter{jj} = m_iter; 
        end

        parfor (jj = 1:length(rho_vec)) 
            try
                m_vec_iter{jj} = workhorse_nested_robust(m_vec_iter{jj});
                gveciter(jj) = m_vec_iter{jj}.growth_rate; 

                if (m_vec_iter{jj}.kappa >= 9999)
                    markup_mean_iter(jj) = m_vec_iter{jj}.markup; 
                else
                    markup_mean_iter(jj) = m_vec_iter{jj}.markup_wt-1;
                end

                [markup_p50_iter(jj), markup_array, gmarkup_all] = markup_quant(m_vec_iter{jj}.kappa, m_vec_iter{jj}.lambda, ...
                                                                                m_vec_iter{jj}.s_max, m_vec_iter{jj}.firm_distributions, ...
                                                                                m_vec_iter{jj}.nu_s, 0.5);
                [markup_p90_iter(jj), markup_array, gmarkup_all] = markup_quant(m_vec_iter{jj}.kappa, m_vec_iter{jj}.lambda, ...
                                                                                m_vec_iter{jj}.s_max, m_vec_iter{jj}.firm_distributions, ...
                                                                                m_vec_iter{jj}.nu_s, 0.9);
            catch
            end

        end
        gveccollect(ii, :) = gveciter;
        markup_p50_collect(ii, :) = markup_p50_iter;
        markup_p90_collect(ii, :) = markup_p90_iter; 
        markup_mean_collect(ii, :) = markup_mean_iter; 
    
        m = sim_wrap(m); 
        m = CSTAT_sim(m); 
        m = innovation_output(m); 
        if (m.entrance)
                m = FHK_sim(m); 
                m = emp_share_sim(m); 
        end

        [m.p50_approx, ~, ~] = markup_quant(m.kappa, m.lambda, m.s_max, m.firm_distributions, m.nu_s, 0.5);
        [m.p75_approx, ~, ~] = markup_quant(m.kappa, m.lambda, m.s_max, m.firm_distributions, m.nu_s, 0.75);
        [m.p90_approx, m.markup_array, ~] = markup_quant(m.kappa, m.lambda, m.s_max, m.firm_distributions, m.nu_s, 0.9);

        m_collect{ii} = m; 

    end

    rng(2022+08+30, 'Threefry')
    draw_Lerner = betarnd(1.36, 8, 1e6, 1);
    draw_markup = 1./(1-draw_Lerner) - 1; 

    markup_targ = 100*[mean(draw_markup), prctile(draw_markup, [50, 90])]; 
    target_filter_vec = ["three_dropm1", "three_dropm1_nothreeqtr", "three_dropm1_noposRD"]; 
    kogan_str = ["Output/Store_Data/kogan_targets.csv", "Output/Store_Data/kogan_targets.csv", ...
                "Output/Store_Data/kogan_targets_glscincludeFALSE.csv"];
    total_prod = 3.44 + -.41 + .76 + 1.23 + .12; 
    ENTRANCE_data = 1.23/total_prod;
    WITHIN_data = 3.44/total_prod;
    BETWEEN_data = -.41/total_prod;
    CROSS_data = .76/total_prod;
    EXIT_data = .12/total_prod;
            
    FHK_targ = 100*[WITHIN_data*total_prod/(total_prod - ENTRANCE_data*total_prod - EXIT_data*total_prod), ...
                            BETWEEN_data*total_prod/(total_prod - ENTRANCE_data*total_prod - EXIT_data*total_prod), ...
                            CROSS_data*total_prod/(total_prod - ENTRANCE_data*total_prod - EXIT_data*total_prod), ...
                            1e-8,1e-8];
    FHK_targ_ent = 100*[WITHIN_data, BETWEEN_data, CROSS_data, ENTRANCE_data, EXIT_data];
    share10_targ = 26.19;
    share5_targ = 15.68;
    targets_cell = cell(1, size(target_filter_vec, 2)); 
    growth_targ = 1.033; 
    for (ii = 1:size(target_filter_vec, 2))
            
            targ = struct(); 

            targ.rdsales_targets = readtable(strcat("Output/Store_Data/rdsales_t_targets_", target_filter_vec(ii), ".csv")); 
            targ.profvol_targets = readtable(strcat("Output/Store_Data/profitvol_t_", target_filter_vec(ii), ".csv")); 
            targ.uncond_IO_targets = readmatrix(kogan_str(ii));

            targets_cell{ii} = targ; 

            

    end
    clear draw_markup;
    clear draw_Lerner; 

    
    params = zeros(length(models), 13); 
    for (ii = 1:size(params, 1)) 
        m = models{ii}(); 

        params(ii, :)  = [m.phi_wt, m.B, m.lambda, m.kappa, nan, m.rho, m.gamma, m.phi_wt_tilde, m.B_entrant, ...
                            m.phi_wt_exog, m.l, m.l_tilde, m.eta(2)];
    end


    smain = strcat("\begin{adjustbox}{center} \begin{tabular}{lcccccc}  \hline\hline Moments & $\gamma = 0.33$ & $\kappa = 12$ & ", ...
                " $\eta =0.03$ & $\varphi = 0.50$   & \shortstack{Inelastic\\labor} & Data \\  ", ...
                " \hline Productivity growth & ", num2str(100*(power(1+m_collect{7}.growth_rate,12)-1), '%0.2f'), "\%", " & ", ...
                        num2str(100*(power(1+m_collect{9}.growth_rate,12)-1), '%0.2f'), "\%",  " & ", ...
                        num2str(100*(power(1+m_collect{8}.growth_rate, 12)-1), '%0.2f'), "\%", " & ", ...
                        num2str(100*(power(1+m_collect{6}.growth_rate,12)-1), '%0.2f'), "\%", " & ", ...
                        num2str(100*(power(1+m_collect{1}.growth_rate,12)-1), '%0.2f'), "\%", " & ", ...
                        num2str(growth_targ, '%0.2f'), "\%", " \\ ", ...
                " Mean markup & ", num2str(100*m_collect{7}.markup, '%0.2f'), "\%", " & ", ...
                num2str(100*(m_collect{9}.markup_wt-1), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{8}.markup, '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{6}.markup, '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{1}.markup, '%0.2f'), "\%", " & ", ...
                num2str(markup_targ(1), '%0.2f'), "\%", " \\ ", ...
                " Profit volatility \\ ", ...
                " \hspace{0.2in} All firms & ", num2str(100*m_collect{7}.std_table.mean_fun1_profitgrowth_w(end), '%0.2f'), "\%", ...
                " & ", num2str(100*m_collect{9}.std_table.mean_fun1_profitgrowth_w(end), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{8}.std_table.mean_fun1_profitgrowth_w(end), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{6}.std_table.mean_fun1_profitgrowth_w(end), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{1}.std_table.mean_fun1_profitgrowth_w(end), '%0.2f'), "\%", " & ", ...
                num2str(100*targets_cell{1}.profvol_targets.sd(end), '%0.2f'), "\%", " \\ ", ...
                " \hspace{0.2in} Top profit quintile & ", num2str(100*m_collect{7}.std_table.mean_fun1_profitgrowth_w(1), '%0.2f'), ...
                "\%", " & ", num2str(100*m_collect{9}.std_table.mean_fun1_profitgrowth_w(1), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{8}.std_table.mean_fun1_profitgrowth_w(1), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{6}.std_table.mean_fun1_profitgrowth_w(1), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{1}.std_table.mean_fun1_profitgrowth_w(1), '%0.2f'), "\%", " & ", ...
                num2str(100*targets_cell{1}.profvol_targets.sd(1), '%0.2f'), "\%", " \\ ", ...
                " R\&D to sales \\ ", ...
                " \hspace{0.2in} All firms & ", num2str(100*m_collect{7}.std_table.mean_fun2_rdsales_w(end), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{9}.std_table.mean_fun2_rdsales_w(end), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{8}.std_table.mean_fun2_rdsales_w(end), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{6}.std_table.mean_fun2_rdsales_w(end), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{1}.std_table.mean_fun2_rdsales_w(end), '%0.2f'), "\%", " & ", ...
                num2str(100*targets_cell{1}.rdsales_targets.p50(end), '%0.2f'), "\%", " \\ ", ...
                " \hspace{0.2in} Top profit quintile & ", num2str(100*m_collect{7}.std_table.mean_fun2_rdsales_w(1), '%0.2f'), ...
                "\%", " & ", num2str(100*m_collect{9}.std_table.mean_fun2_rdsales_w(1), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{8}.std_table.mean_fun2_rdsales_w(1), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{6}.std_table.mean_fun2_rdsales_w(1), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{1}.std_table.mean_fun2_rdsales_w(1), '%0.2f'), "\%", " & ", ...
                num2str(100*targets_cell{1}.rdsales_targets.p50(1), '%0.2f'), "\%", " \\ ", ...
                " Innovation output \\ ", ...
                " \hspace{0.2in} Mean & ", num2str(100*m_collect{7}.uncond_IO(1), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{9}.uncond_IO(1), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{8}.uncond_IO(1), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{6}.uncond_IO(1), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{1}.uncond_IO(1), '%0.2f'), "\%", " & ", ...
                num2str(targets_cell{1}.uncond_IO_targets(1), '%0.2f'), "\%", " \\ ", ...
                " \hspace{0.2in} 90th percentile & ", num2str(100*m_collect{7}.uncond_IO(9), '%0.2f'), "\%", " & ",  ...
                num2str(100*m_collect{9}.uncond_IO(9), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{8}.uncond_IO(9), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{6}.uncond_IO(9), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{1}.uncond_IO(9), '%0.2f'), "\%", " & ", ...
                num2str(targets_cell{1}.uncond_IO_targets(9), '%0.2f'), "\%", " \\ ", ...
                "\hline \hline Parameters \\ ", ...
                " \hline $\phi$ & ", num2str(params(7, 1), '%0.3f'), " & ", num2str(params(9, 1), '%0.3f'), " & ", num2str(params(8, 1), '%0.3f'), " & ", ... 
                    num2str(params(6, 1), '%0.3f'), " & ", num2str(params(1, 1), '%0.3f'), " & ", " \\ ", ...
                " $100 \cdot \ln (\lambda)$ & ",  num2str(100*log(params(7, 3)), '%0.3f'), " & ",num2str(100*log(params(9, 3)), '%0.3f'), " & ", num2str(100*log(params(8, 3)), '%0.3f'), " & ", ... 
                num2str(100*log(params(6, 3)), '%0.3f'), " & ", num2str(100*log(params(1, 3)), '%0.3f'), " & ", " \\ ", ...
                " $B$ & ", num2str(12*params(7, 2), '%0.3f'), " & ", num2str(12*params(9, 2), '%0.3f'), " & ", num2str(12*params(8, 2), '%0.3f'), " & ", ... 
                num2str(12*params(6, 2), '%0.3f'), " & ", num2str(12*params(1, 2), '%0.3f'), " & ", " \\ ", ...
                "\hline \end{tabular} \end{adjustbox} "); 

    writematrix(smain, "Output/LaTeX_Output/robustnessmain.txt", 'QuoteStrings', false);

    sia = strcat("\begin{tabular}{lccccccc}  \hline\hline Moments & $\gamma = 0.66$ &  $\kappa = 24$ & $\kappa = 36$ & $\eta = 0.06$ & ", ...
                " $\varphi = 0.25$  & $\rho = 1.5\%$ &  Data \\ ",...
                " \hline  Productivity growth  & ", num2str(100*(power(1+m_collect{2}.growth_rate, 12)-1), '%0.2f'), "\%", " & ", ...
                        num2str(100*(power(1+m_collect{10}.growth_rate,12)-1), '%0.2f'), "\%", ...
                    " & ", num2str(100*(power(1+m_collect{11}.growth_rate,12)-1), '%0.2f'), "\%", " & ", ...
                    num2str(100*(power(1+m_collect{3}.growth_rate,12)-1), '%0.2f'), "\%", " & ", ...
                    num2str(100*(power(1+m_collect{5}.growth_rate,12)-1), '%0.2f'), "\%", " & ", ...
                    num2str(100*(power(1+m_collect{4}.growth_rate,12)-1), '%0.2f'), "\%", " & ", ...
                    num2str(growth_targ, '%0.2f'), "\%",  "  \\  ", ...
                " Mean markup & ", num2str(100*m_collect{2}.markup, '%0.2f'), "\%", " & ",  ...
                num2str(100*(m_collect{10}.markup_wt-1), '%0.2f'), "\%", ...
                " & ", num2str(100*(m_collect{11}.markup_wt-1), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{3}.markup, '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{5}.markup, '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{4}.markup, '%0.2f'), "\%", " & ", ...
                num2str(markup_targ(1), '%0.2f'), "\%",  "  \\  ", ...
                "  Profit volatility  \\ ", ...
                " \hspace{0.2in}  All firms  & ", num2str(100*m_collect{2}.std_table.mean_fun1_profitgrowth_w(end), '%0.2f'), "\%", ...
                " & ", num2str(100*m_collect{10}.std_table.mean_fun1_profitgrowth_w(end), '%0.2f'), "\%", ...
                " & ", num2str(100*m_collect{11}.std_table.mean_fun1_profitgrowth_w(end), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{3}.std_table.mean_fun1_profitgrowth_w(end), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{5}.std_table.mean_fun1_profitgrowth_w(end), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{4}.std_table.mean_fun1_profitgrowth_w(end), '%0.2f'), "\%", " & ", ...
                num2str(100*targets_cell{1}.profvol_targets.sd(end), '%0.2f'), "\%",  "  \\  ", ...
                " \hspace{0.2in}  Top profit quintile  & ", num2str(100*m_collect{2}.std_table.mean_fun1_profitgrowth_w(1), '%0.2f'), ...
                "\%", " & ", num2str(100*m_collect{10}.std_table.mean_fun1_profitgrowth_w(1), '%0.2f'), "\%", ...
                " & ", num2str(100*m_collect{11}.std_table.mean_fun1_profitgrowth_w(1), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{3}.std_table.mean_fun1_profitgrowth_w(1), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{5}.std_table.mean_fun1_profitgrowth_w(1), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{4}.std_table.mean_fun1_profitgrowth_w(1), '%0.2f'), "\%", " & ", ...
                num2str(100*targets_cell{1}.profvol_targets.sd(1), '%0.2f'), "\%",  "  \\  ", ...
                "  R\&D to sales  \\ ", ...
                " \hspace{0.2in} All firms  & ", num2str(100*m_collect{2}.std_table.mean_fun2_rdsales_w(end), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{10}.std_table.mean_fun2_rdsales_w(end), '%0.2f'), "\%", ...
                " & ", num2str(100*m_collect{11}.std_table.mean_fun2_rdsales_w(end), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{3}.std_table.mean_fun2_rdsales_w(end), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{5}.std_table.mean_fun2_rdsales_w(end), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{4}.std_table.mean_fun2_rdsales_w(end), '%0.2f'), "\%", " & ", ...
                num2str(100*targets_cell{1}.rdsales_targets.p50(end), '%0.2f'), "\%",  "  \\  ", ...
                " \hspace{0.2in}  Top profit quintile  & ", num2str(100*m_collect{2}.std_table.mean_fun2_rdsales_w(1), '%0.2f'), "\%", ...
                " & ",  num2str(100*m_collect{10}.std_table.mean_fun2_rdsales_w(1), '%0.2f'), "\%", ...
                " & ", num2str(100*m_collect{11}.std_table.mean_fun2_rdsales_w(1), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{3}.std_table.mean_fun2_rdsales_w(1), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{5}.std_table.mean_fun2_rdsales_w(1), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{4}.std_table.mean_fun2_rdsales_w(1), '%0.2f'), "\%", " & ", ...
                num2str(targets_cell{1}.rdsales_targets.p50(1), '%0.2f'), "\%",  "  \\  ", ...
                "  Innovation output  \\ ", ...
                " \hspace{0.2in} Mean  & ", num2str(100*m_collect{2}.uncond_IO(1), '%0.2f'), "\%", " & ",  ...
                num2str(100*m_collect{10}.uncond_IO(1), '%0.2f'), "\%", ...
                " & ", num2str(100*m_collect{11}.uncond_IO(1), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{3}.uncond_IO(1), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{5}.uncond_IO(1), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{4}.uncond_IO(1), '%0.2f'), "\%", " & ", ...
                num2str(targets_cell{1}.uncond_IO_targets(1), '%0.2f'), "\%",  "  \\  ", ...
                " \hspace{0.2in}  90th percentile  & ", num2str(100*m_collect{2}.uncond_IO(9), '%0.2f'), "\%", " & ",  ...
                num2str(100*m_collect{10}.uncond_IO(9), '%0.2f'), "\%", ...
                " & ", num2str(100*m_collect{11}.uncond_IO(9), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{3}.uncond_IO(9), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{5}.uncond_IO(9), '%0.2f'), "\%", " & ", ...
                num2str(100*m_collect{4}.uncond_IO(9), '%0.2f'), "\%", " & ", ...
                num2str(targets_cell{1}.uncond_IO_targets(9), '%0.2f'), "\%",  "  \\  ", ...
                "\hline \hline Parameter \\ ", ...
                "\hline $\phi$ & ", num2str(params(2,1), '%0.3f'), " & ", num2str(params(10, 1), '%0.3f'), " & ",  num2str(params(11, 1), '%0.3f'),  " & ", ...
                num2str(params(3,1), '%0.3f'), " & ", num2str(params(5,1), '%0.3f'), " & ", ...
                num2str(params(4,1), '%0.3f'), " & ", "  \\  ", ...
                " $\lambda$ & ", num2str(params(2,3), '%0.3f'), " & ",  num2str(params(10, 3), '%0.3f'), " & ", num2str(params(11, 3), '%0.3f'), " & ", ...
                num2str(params(3,3), '%0.3f'), " & ", num2str(params(5,3), '%0.3f'), " & ", ...
                num2str(params(4,3), '%0.3f'), " & ", "  \\  ", ...
                " $B$ & ",  num2str(12*params(2,2), '%0.3f'), " & ",  num2str(12*params(10, 2), '%0.3f'), " & ",  num2str(params(11,2)*12, '%0.3f'), " & ", ...
                num2str(12*params(3,2), '%0.3f'), " & ", num2str(12*params(5,2), '%0.3f'), " & ", ...
                num2str(12*params(4,2), '%0.3f'), " & ", "  \\  ", ...
                "\hline \end{tabular}");

    writematrix(sia, "Output/LaTeX_Output/robustness_IA.txt", 'QuoteStrings', false);



    markups_high = readtable("Output/Store_Data/deloecker_etal_targets.csv");
    mean_targ = 100*(markups_high.mean-1);
    p50_targ = 100*(markups_high.p50-1);
    p75_targ = 100*(markups_high.p75-1);
    p90_targ = 100*(markups_high.p90-1);

    s_highmarkup = "\begin{tabular}{lcc} \hline \hline  Moments  & Model & Data  \\  " + ...
                    " \hline  Productivity growth & " + num2str(100*(power(1+m_collect{12}.growth_rate,12)-1),'%0.2f') + "\%" + " & " + ...
                            num2str(growth_targ, '%0.2f') + "\% \\ " + ... 
                    " Markup \\ " + ...
                    " \hspace{0.2in} Mean & " + num2str(100*m_collect{12}.markup, '%0.2f') + "\%" + " & " + ...
                            num2str(mean_targ, '%0.2f') + "\% \\ " + ... 
                    " \hspace{0.2in} 50th percentile & " + num2str(100*(m_collect{12}.p50_approx-1), '%0.2f') + "\%" + " & " + ...
                            num2str(p50_targ, '%0.2f') + "\% \\ " + ... 
                    " \hspace{0.2in} 75th percentile & " + num2str(100*(m_collect{12}.p75_approx-1), '%0.2f') + "\%" + " & " + ...
                            num2str(p75_targ, '%0.2f') + "\% \\ " + ... 
                    " \hspace{0.2in} 90th percentile & " + num2str(100*(m_collect{12}.p90_approx-1), '%0.2f') + "\%" + " & " + ...
                            num2str(p90_targ, '%0.2f') + "\% \\ " + ... 
                    " Profit volatility \\ " + ...
                    " \hspace{0.2in} All firms & " + num2str(100*m_collect{12}.std_table.mean_fun1_profitgrowth_w(end), '%0.2f') + "\%" + " & " + ...
                    num2str(100*targets_cell{1}.profvol_targets.sd(end), '%0.2f') + "\% \\ " + ... 
                    " \hspace{0.2in} Top profit quintile & " + num2str(100*m_collect{12}.std_table.mean_fun1_profitgrowth_w(1), '%0.2f') + "\%" + " & " + ...
                    num2str(100*targets_cell{1}.profvol_targets.sd(1), '%0.2f') + "\% \\ " + ... 
                    " R\&D to sales \\ " + ...
                    " \hspace{0.2in} All firms & " + num2str(100*m_collect{12}.std_table.mean_fun2_rdsales_w(end), '%0.2f') + "\%" + " & " + ...
                    num2str(100*targets_cell{1}.rdsales_targets.p50(end), '%0.2f') + "\% \\ " + ... 
                    " \hspace{0.2in} Top profit quintile & " + num2str(100*m_collect{12}.std_table.mean_fun2_rdsales_w(1), '%0.2f') + "\%" + " & " + ...
                    num2str(100*targets_cell{1}.rdsales_targets.p50(1), '%0.2f') + "\% \\ " + ... 
                    " Innovation output \\ " + ...
                    " \hspace{0.2in} Mean & " + num2str(100*m_collect{12}.uncond_IO(1), '%0.2f') + "\%" + " & " + ...
                    num2str(targets_cell{1}.uncond_IO_targets(1), '%0.2f') + "\% \\ " + ... 
                    " \hspace{0.2in} 90th percentile & " + num2str(100*m_collect{12}.uncond_IO(9), '%0.2f') + "\%" + " & " + ...
                    num2str(targets_cell{1}.uncond_IO_targets(9), '%0.2f') + "\% \\ " + ... 
                    " \hline \hline Parameters \\ " + ...
                    " \hline $\phi$ & " + num2str(params(12,1), '%0.3f') + " & \\ "  + ...
                    " $\lambda$ & " + num2str(params(12,3), '%0.3f') + " & \\" + ...
                    " $B$ & " + num2str(12*params(12,2), '%0.3f') + " & \\ " + ...
                    " \hline \end{tabular}";
    writematrix(s_highmarkup, "Output/LaTeX_Output/highmarkup_tab.txt", 'QuoteStrings', false);

    s_entry_2 = "\begin{tabular}{lcc} " + ...
                " \hline \hline Moments & Model with entry & Data \\ " + ...
                " \hline Profit volatility \\ " + ...
                " \hspace{0.2in} All firms & " + ...
                        num2str(m_collect{13}.std_table.mean_fun1_profitgrowth_w(end)*100, '%0.2f') + ...
                        "\%" + " & " + ...
                        num2str(targets_cell{1}.profvol_targets.sd(end)*100, '%0.2f') + "\%" + " \\ " + ...
                " \hspace{0.2in} Top profit quintile & " + ...
                        num2str(m_collect{13}.std_table.mean_fun1_profitgrowth_w(1)*100, '%0.2f') + "\%" +  ...
                        " & " + ...
                        num2str(targets_cell{1}.profvol_targets.sd(1)*100, '%0.2f') + "\%" + " \\ " + ...
                " R\&D to sales \\ " + ...
                " \hspace{0.2in} All firms & " + ...
                        num2str(m_collect{13}.std_table.mean_fun2_rdsales_w(end)*100, '%0.2f') + "\%" + " & " + ...
                        num2str(targets_cell{1}.rdsales_targets.p50(end)*100, '%0.2f') + "\%" + " \\ "  + ...
                " \hspace{0.2in} Top profit quintile & " + ...
                        num2str(m_collect{13}.std_table.mean_fun2_rdsales_w(1)*100, '%0.2f') + "\%" + " & " + ...
                        num2str(targets_cell{1}.rdsales_targets.p50(1)*100, '%0.2f') + "\%" + " \\ " + ...
                " Innovation output \\ " + ... 
                " \hspace{0.2in} Mean & " + ...
                        num2str(m_collect{13}.uncond_IO(1)*100, '%0.2f') + "\%" + " & " + ...
                        num2str(targets_cell{1}.uncond_IO_targets(1), '%0.2f') + "\%" + " \\ " + ...
                " \hspace{0.2in} 90th percentile & " + ...
                        num2str(m_collect{13}.uncond_IO(9)*100, '%0.2f') + "\%" + " & " + ...
                        num2str(targets_cell{1}.uncond_IO_targets(9), '%0.2f') + "\%" + " \\ " + ...
                " \hline  \end{tabular}";

    s_entry = "\begin{tabular}{lcc}  \hline\hline Moments & \shortstack{Model \\ With Entry} & Data \\ \hline   " + ...
                " Productivity growth & " + num2str(100*(power(1+m_collect{13}.growth_rate,12)-1), '%0.2f') + "\%" + " & " + ...
                    num2str(growth_targ, '%0.2f') + "\% \\ " + ...
                " Mean markup & " + num2str(100*m_collect{13}.markup, '%0.2f') +  "\% & " +  ...
                    num2str(markup_targ(1), '%0.2f') + "\% \\ " + ...
                " FHK decomposition (Entry) & " +  num2str(100*m_collect{13}.ENTRY_out, '%0.2f') + "\% & " + ...
                    num2str(FHK_targ_ent(4), '%0.2f') + "\% \\ " + ...
                " Employment share, $\leq 10$ years & " + num2str(100*m_collect{13}.share10, '%0.2f') + "\% & " + ...
                    num2str(share10_targ, '%0.2f') + "\% \\ " + ...
                " Employment share, $\leq 5$ years & " + num2str(100*m_collect{13}.share5, '%0.2f') + "\% & " + ...
                    num2str(share5_targ, '%0.2f') + "\% \\ " + ...
                " \hline \hline Parameters & &  \\ " + ...
                " \hline  $\phi$ & " + num2str(params(13, 1), '%0.3f') + " & \\ " + ...
                " $\lambda$ & " + num2str(params(13,3), '%0.3f') + " & \\ " + ...
                " $B$ & " + num2str(12*params(13,2), '%0.3f') + " & \\ " + ...
                " $\phi_E$ & " + num2str(params(13,8), '%0.3f') + " & \\ " + ...
                " $B_E$ & " + num2str(12*params(13,9), '%0.3f') + " & \\ " + ...
                " $l_E$ & " + num2str(params(13,12)) + " & \\  \hline  \end{tabular}";

    writematrix(s_entry, "Output/LaTeX_Output/entry_tab.txt", 'QuoteStrings', false); 
    writematrix(s_entry_2, "Output/LaTeX_Output/entry_tab_2.txt", 'QuoteStrings', false); 



    s_OI = "\begin{tabular}{lcc}  \hline \hline Moments & Model  & Data \\ " + ...
            "\hline Productivity growth & " + num2str(100*(power(1+m_collect{18}.growth_rate, 12)-1), '%0.2f') + "\%" + " & " + ...
                    num2str(0.76, '%0.2f') + "\%" + " \\ " + ...
            " Markups \\ " + ...
            " \hspace{0.2in} Mean & " + num2str(100*(m_collect{18}.markup_wt-1), '%0.2f') + "\%" + " & " + ...
                    num2str(markup_targ(1), '%0.2f') + "\%" + " \\ " + ...
            " \hspace{0.2in} 50th percentile & " + num2str(100*(m_collect{18}.p50_approx-1), '%0.2f') + "\%" + " & " + ...
                    num2str(markup_targ(2), '%0.2f') + "\%" + " \\ " + ...
            " \hspace{0.2in} 90th percentile & " + num2str(100*(m_collect{18}.p90_approx-1), '%0.2f') + "\%" + " & " + ...
                    num2str(markup_targ(3), '%0.2f') + "\%" + " \\ " + ...
            "Profit volatility \\ " + ...
            " \hspace{0.2in} All firms & " + num2str(100*m_collect{18}.std_table.mean_fun1_profitgrowth_w(end), '%0.2f') + "\%" + " & " + ...
                    num2str(100*targets_cell{1}.profvol_targets.sd(end), '%0.2f') + "\%" + " \\ " + ...
            " \hspace{0.2in} Top profit quintile & " + num2str(100*m_collect{18}.std_table.mean_fun1_profitgrowth_w(1), '%0.2f') + "\%" + " & " + ...
                    num2str(100*targets_cell{1}.profvol_targets.sd(1), '%0.2f') + "\%" + " \\ " + ...
            " R\&D to sales \\ " + ...
            " \hspace{0.2in} All firms & " + num2str(100*m_collect{18}.std_table.mean_fun2_rdsales_w(end), '%0.2f') + "\%" + " & " + ...
                    num2str(100*targets_cell{1}.rdsales_targets.p50(end), '%0.2f') + "\%" + " \\ " + ...
            " \hspace{0.2in} Top profit quintile & " + num2str(100*m_collect{18}.std_table.mean_fun2_rdsales_w(1), '%0.2f') + "\%" + " & " + ...
                    num2str(100*targets_cell{1}.rdsales_targets.p50(1), '%0.2f') + "\%" + " \\ " + ...
            " Innovation output \\ " + ...
            " \hspace{0.2in} Mean & " + num2str(100*m_collect{18}.uncond_IO(1), '%0.2f') + "\%" + " & " + ...
                    num2str(targets_cell{1}.uncond_IO_targets(1), '%0.2f') + "\% \\ " + ... 
                    " \hspace{0.2in} 90th percentile & " + num2str(100*m_collect{18}.uncond_IO(9), '%0.2f') + "\%" + " & " + ...
                    num2str(targets_cell{1}.uncond_IO_targets(9), '%0.2f') + "\% \\ " + ... 
            "\hline \hline Parameters \\ " + ...
            " \hline $B$ & " + num2str(params(18, 2)*12, '%0.3f') + " \\ " + ...
            " $\lambda$ & " + num2str(params(18, 3), '%0.3f') + " \\ " + ...
            " $\eta$ & " + num2str(params(18, 13)*12, '%0.3f') + " \\ " + ...
            " \hline \end{tabular}"; 

    writematrix(s_OI, "Output/LaTeX_Output/OI_03p.txt", 'QuoteStrings', false); 


s_OI_2 = "\begin{tabular}{lcc}  \hline \hline Moments & Model  & Data \\ " + ...
            "\hline Productivity growth & " + num2str(100*(power(1+m_collect{19}.growth_rate, 12)-1), '%0.2f') + "\%" + " & " + ...
                    num2str(1.10, '%0.2f') + "\%" + " \\ " + ...
            " Markups \\ " + ...
            " \hspace{0.2in} Mean & " + num2str(100*(m_collect{19}.markup_wt-1), '%0.2f') + "\%" + " & " + ...
                    num2str(markup_targ(1), '%0.2f') + "\%" + " \\ " + ...
            " \hspace{0.2in} 50th percentile & " + num2str(100*(m_collect{19}.p50_approx-1), '%0.2f') + "\%" + " & " + ...
                    num2str(markup_targ(2), '%0.2f') + "\%" + " \\ " + ...
            " \hspace{0.2in} 90th percentile & " + num2str(100*(m_collect{19}.p90_approx-1), '%0.2f') + "\%" + " & " + ...
                    num2str(markup_targ(3), '%0.2f') + "\%" + " \\ " + ...
            "Profit volatility \\ " + ...
            " \hspace{0.2in} All firms & " + num2str(100*m_collect{19}.std_table.mean_fun1_profitgrowth_w(end), '%0.2f') + "\%" + " & " + ...
                    num2str(100*targets_cell{1}.profvol_targets.sd(end), '%0.2f') + "\%" + " \\ " + ...
            " \hspace{0.2in} Top profit quintile & " + num2str(100*m_collect{19}.std_table.mean_fun1_profitgrowth_w(1), '%0.2f') + "\%" + " & " + ...
                    num2str(100*targets_cell{1}.profvol_targets.sd(1), '%0.2f') + "\%" + " \\ " + ...
            " R\&D to sales \\ " + ...
            " \hspace{0.2in} All firms & " + num2str(100*m_collect{19}.std_table.mean_fun2_rdsales_w(end), '%0.2f') + "\%" + " & " + ...
                    num2str(100*targets_cell{1}.rdsales_targets.p50(end), '%0.2f') + "\%" + " \\ " + ...
            " \hspace{0.2in} Top profit quintile & " + num2str(100*m_collect{19}.std_table.mean_fun2_rdsales_w(1), '%0.2f') + "\%" + " & " + ...
                    num2str(100*targets_cell{1}.rdsales_targets.p50(1), '%0.2f') + "\%" + " \\ " + ...
            " Innovation output \\ " + ...
            " \hspace{0.2in} Mean & " + num2str(100*m_collect{19}.uncond_IO(1), '%0.2f') + "\%" + " & " + ...
                    num2str(targets_cell{1}.uncond_IO_targets(1), '%0.2f') + "\% \\ " + ... 
                    " \hspace{0.2in} 90th percentile & " + num2str(100*m_collect{19}.uncond_IO(9), '%0.2f') + "\%" + " & " + ...
                    num2str(targets_cell{1}.uncond_IO_targets(9), '%0.2f') + "\% \\ " + ... 
            "\hline \hline Parameters \\ " + ...
            " \hline $B$ & " + num2str(params(19, 2)*12, '%0.3f') + " \\ " + ...
            " $\lambda$ & " + num2str(params(19, 3), '%0.3f') + " \\ " + ...
            " $\eta$ & " + num2str(params(19, 13)*12, '%0.3f') + " \\ " + ...
            " \hline \end{tabular}"; 


    writematrix(s_OI_2, "Output/LaTeX_Output/OI_3p.txt", 'QuoteStrings', false); 



    s_cstat_alt = "\begin{tabular}{lcccccc} \hline \hline  & \multicolumn{2}{c}{No pos. R\&D} & & \multicolumn{2}{c}{No 3 qtr. profit} \\  " + ...
                    " \cline{2-3} \cline{5-6}  Moments & Model & Target &  & Model & Target \\  " + ...
                    " \hline  Productivity growth  & " + num2str(100*(power(1+m_collect{17}.growth_rate, 12)-1), '%0.2f') + "\% & " + ...
                            num2str(growth_targ, '%0.2f') + "\%  & & " + ...
                        num2str(100*(power(1+m_collect{15}.growth_rate, 12)-1), '%0.2f') + "\% & " + ...
                                num2str(growth_targ, '%0.2f') +  "\% \\ " + ...
                    "  Mean markup  & " + num2str(100*m_collect{17}.markup, '%0.2f') + "\% & " + ...
                        num2str(markup_targ(1), '%0.2f') + "\%  & & " + ...
                    num2str(100*m_collect{15}.markup, '%0.2f') + "\% & " + num2str(markup_targ(1), '%0.2f') + "\% \\ " + ...
                    " Profit volatility \\ " + ...
                    "  \hspace{0.2in} All firms  & " + num2str(100*m_collect{17}.std_table.mean_fun1_profitgrowth_w(end), '%0.2f') + "\% & " + ...
                        num2str(100*targets_cell{3}.profvol_targets.sd(end), '%0.2f') + "\%  & & " + ...
                    num2str(100*m_collect{15}.std_table.mean_fun1_profitgrowth_w(end), '%0.2f') + "\% & " + ...
                    num2str(100*targets_cell{2}.profvol_targets.sd(end), '%0.2f') + "\% \\ " + ...
                    "  \hspace{0.2in} Top profit quintile  & " + num2str(100*m_collect{17}.std_table.mean_fun1_profitgrowth_w(1), '%0.2f') + "\% & " + ...
                        num2str(100*targets_cell{3}.profvol_targets.sd(1), '%0.2f') + "\%  & & " + ...
                    num2str(100*m_collect{15}.std_table.mean_fun1_profitgrowth_w(1), '%0.2f') + "\% & " + ...
                        num2str(100*targets_cell{2}.profvol_targets.sd(1), '%0.2f') +  "\% \\ " + ...
                    " R\&D to sales \\ " + ...
                    "  \hspace{0.2in} All firms  & " + num2str(100*m_collect{17}.std_table.mean_fun2_rdsales_w(end), '%0.2f') + "\% & " + ...
                    num2str(100*targets_cell{3}.rdsales_targets.p50(end), '%0.2f') + "\%  & & " + ...
                        num2str(100*m_collect{15}.std_table.mean_fun2_rdsales_w(end), '%0.2f') + "\% & " + ...
                        num2str(100*targets_cell{2}.rdsales_targets.p50(end),'%0.2f') + "\% \\ " + ...
                    "  \hspace{0.2in} Top profit quintile  & " + num2str(100*m_collect{17}.std_table.mean_fun2_rdsales_w(1), '%0.2f') + "\% & " + ...
                    num2str(100*targets_cell{3}.rdsales_targets.p50(1), '%0.2f') + "\%  & & " + ...
                        num2str(100*m_collect{15}.std_table.mean_fun2_rdsales_w(1), '%0.2f') + "\% & " + ...
                        num2str(100*targets_cell{2}.rdsales_targets.p50(1), '%0.2f') +  "\% \\ " + ...
                    " Innovation output \\ " + ...
                    "  \hspace{0.2in} Mean  & " + num2str(100*m_collect{17}.uncond_IO(1), '%0.2f') + "\% & " + ...
                    num2str(targets_cell{3}.uncond_IO_targets(1), '%0.2f') + "\%  & & " + ...
                        num2str(100*m_collect{15}.uncond_IO(1), '%0.2f') + "\% & " + ...
                        num2str(targets_cell{2}.uncond_IO_targets(1), '%0.2f') +  "\% \\ " + ...
                        "  \hspace{0.2in} 90th percentile  & " + num2str(100*m_collect{17}.uncond_IO(9), '%0.2f') + "\% & " + ...
                    num2str(targets_cell{3}.uncond_IO_targets(9), '%0.2f') + "\%  & & " + ...
                            num2str(100*m_collect{15}.uncond_IO(9), '%0.2f') + "\% & " + ...
                            num2str(targets_cell{2}.uncond_IO_targets(9), '%0.2f') +  "\% \\ " + ...
                    " \hline \hline Parameters \\ " + ...
                    " \hline $\phi$ & " + num2str(params(17, 1), '%0.3f') + " & & & " + num2str(params(15, 1), '%0.3f') +  " \\ " + ...
                    " $\lambda$ & " + num2str(params(17, 3), '%0.3f') + " & & & " + num2str(params(15, 3), '%0.3f') + " \\ " + ...
                    " $B$ & " + num2str(params(17, 2)*12, '%0.3f') + " & & & " + num2str(params(15, 2)*12, '%0.3f') + " \\ \hline \end{tabular}"; 
                                

    writematrix(s_cstat_alt, "Output/LaTeX_Output/cstat_alt.txt", 'QuoteStrings', false); 

    s_finfric = "\begin{tabular}{lcc} \hline \hline Moments & $\beta = 0.1$ & Data \\  " + ...
                " \hline Productivity growth  & " + num2str(100*(power(1+m_collect{16}.growth_rate,12)-1), '%0.2f') + "\% & " + ...
                        num2str(growth_targ, '%0.2f') + "\% \\ " + ...
                " Mean markup & " + num2str(100*m_collect{16}.markup,'%0.2f') + "\% & " + num2str(markup_targ(1), '%0.2f') + "\% \\ " + ...
                " Profit volatility \\ " + ...
                " \hspace{0.2in} All firms & " + num2str(100*m_collect{16}.std_table.mean_fun1_profitgrowth_w(end),'%0.2f') + "\% & " + ...
                        num2str(100*targets_cell{1}.profvol_targets.sd(end), '%0.2f') + "\% \\ " + ...
                " \hspace{0.2in} Top profit quintile & " + num2str(100*m_collect{16}.std_table.mean_fun1_profitgrowth_w(1),'%0.2f') + ...
                        "\% & " + num2str(100*targets_cell{1}.profvol_targets.sd(1), '%0.2f') + "\% \\ " + ...
                " R\&D to sales \\ " + ...
                " \hspace{0.2in} All firms & " + num2str(100*m_collect{16}.std_table.mean_fun2_rdsales_w(end),'%0.2f') + "\% & " + ...
                        num2str(100*targets_cell{1}.rdsales_targets.p50(end), '%0.2f') + "\% \\ " + ...
                " \hspace{0.2in} Top profit quintile & " + num2str(100*m_collect{16}.std_table.mean_fun2_rdsales_w(1),'%0.2f') + "\% & " + ...
                        num2str(100*targets_cell{1}.rdsales_targets.p50(1), '%0.2f') +  "\% \\ " + ...
                " Innovation output \\ " + ...
                " \hspace{0.2in} Mean & " + num2str(100*m_collect{16}.uncond_IO(1),'%0.2f') + "\% & " + ...
                        num2str(targets_cell{1}.uncond_IO_targets(1), '%0.2f')+  "\% \\ " + ...
                " \hspace{0.2in} 90th percentile & " + num2str(100*m_collect{16}.uncond_IO(9),'%0.2f') + "\% & " + ...
                        num2str(targets_cell{1}.uncond_IO_targets(9), '%0.2f') +  "\% \\ " + ...
                " \hline \hline Parameters \\ " + ...
                " \hline $\phi$ & " + num2str(params(16, 1), '%0.3f') + " \\ " + ...
                " $\lambda$ & " + num2str(params(16,3), '%0.3f') + " \\ " + ...
                " $B$ & " + num2str(params(16,2)*12, '%0.3f') + " \\ \hline \end{tabular}"; 

    writematrix(s_finfric, "Output/LaTeX_Output/finfric_tab.txt", 'QuoteStrings', false); 



            

    rho_plot = 100*(power(1+rho_vec, 12) - 1); 


    close all 
    figure; 

    set(gcf, 'PaperUnits', 'inches');
    x_width=5.5;
    y_width=2.75;
    set(gcf, 'PaperPosition', [0 0 x_width y_width]); %

    subplot(1,2,1)
    p1 = plot(rho_plot, 100*(power(1+gveccollect(17, :),12)-1), '-r', 'LineWidth', 2);
    hold on ;
    p2 = plot(rho_plot, 100*(power(1+gveccollect(15, :),12)-1), '--r', 'LineWidth', 2);
    xlabel('Discount rate, $\rho$', 'Interpreter', 'latex');
    ylabel('Growth, $g$', 'Interpreter', 'latex');
    l1 = legend([p1,p2], 'No pos. R\&D', 'No 3 qtr. profit', 'Interpreter', 'latex', 'Location', 'northeast');
    set(l1, 'box', 'off');
    xlim([0,5]);

    subplot(1,2,2)
    p1 = plot(rho_plot, 100*(power(1+markup_mean_collect(17, :),1)-1), '-r', 'LineWidth', 2);
    hold on ;
    p2 = plot(rho_plot, 100*(power(1+markup_mean_collect(15, :),1)-1), '--r', 'LineWidth', 2);
    xlabel('Discount rate, $\rho$', 'Interpreter', 'latex');
    ylabel('Mean net markup', 'Interpreter', 'latex');
    xlim([0,5]);


    saveas(gcf, "Output/Figures_Paper/compustat_construct_fig.png");
    saveas(gcf, "Output/Figures_Paper/compustat_construct_fig.eps", 'epsc');


    close all;
    figure; 


    set(gcf, 'PaperUnits', 'inches');
    x_width=3.25;
    y_width=4.2;
    set(gcf, 'PaperPosition', [0 0 x_width y_width]); %

    subplot(2,1,1)
    p1 = plot(rho_plot, 100*(power(1 + gveccollect(19, :), 12)- 1), '--r', 'LineWidth', 2);
    xlabel('Discount rate, $\rho$', 'Interpreter', 'latex');
    ylabel('Growth, $g$', 'Interpreter', 'latex');
    xlim([0,5]);

    subplot(2,1,2)
    p1 = plot(rho_plot, 100*markup_mean_collect(19,:), '--r', 'LineWidth', 2);
    xlabel('Discount rate, $\rho$', 'Interpreter', 'latex');
    ylabel('Mean net markup', 'Interpreter', 'latex');
    xlim([0,5]);
    ylim([20,26]);

    saveas(gcf, "Output/Figures_Paper/oi_3p.png");
    saveas(gcf, "Output/Figures_Paper/oi_3p.eps", 'epsc');


    close all
    figure; 


    set(gcf, 'PaperUnits', 'inches');
    x_width=3.25;
    y_width=4.2;
    set(gcf, 'PaperPosition', [0 0 x_width y_width]); %

    subplot(2,1,1)
    p1 = plot(rho_plot, 100*(power(1 + gveccollect(18, :), 12)- 1), '--r', 'LineWidth', 2);
    xlabel('Discount rate, $\rho$', 'Interpreter', 'latex');
    ylabel('Growth, $g$', 'Interpreter', 'latex');
    xlim([0,5]);

    subplot(2,1,2)
    p1 = plot(rho_plot, 100*markup_mean_collect(18,:), '--r', 'LineWidth', 2);
    xlabel('Discount rate, $\rho$', 'Interpreter', 'latex');
    ylabel('Mean net markup', 'Interpreter', 'latex');
    xlim([0,5]);
    ylim([18,26]);

    saveas(gcf, "Output/Figures_Paper/oi_03p.png");
    saveas(gcf, "Output/Figures_Paper/oi_03p.eps", 'epsc');



    ent_string = categorical(["WITHIN", "BETWEEN", "CROSS", "ENTRY", "EXIT"]); 
    ent_string = reordercats(ent_string, ["WITHIN", "BETWEEN", "CROSS", "ENTRY", "EXIT"]);
    ent_model = [m_collect{13}.WITHIN_out, m_collect{13}.BETWEEN_out, m_collect{13}.CROSS_out, m_collect{13}.ENTRY_out, m_collect{13}.EXIT_out]; 
        

    close all 
    figure;

    set(gcf, 'PaperUnits', 'inches');
    x_width=3.25;
    y_width=3;
    set(gcf, 'PaperPosition', [0 0 x_width y_width]); %


    b1 = bar(ent_string, [FHK_targ_ent', 100*ent_model'], 'FaceColor', 'flat');
    b1(1).CData = [0,0,1];
    b1(2).CData = [1,0,0]; 
    ylabel('Contribution to TFP (\%)', 'Interpreter', 'latex');
    ylim([-20, 100]);
    l1 = legend("Data", "Model", 'Interpreter', 'latex');
    set(l1, 'box', 'off');
    ax = gca;
    ax.XAxis.TickLabelInterpreter= 'latex';
    ax.XAxis.FontSize = 8;

    saveas(gcf, "Output/Figures_Paper/ent_decomp.eps", 'epsc');
    saveas(gcf, "Output/Figures_Paper/ent_decomp.png");



    close all
    figure;

    set(gcf, 'PaperUnits', 'inches');
    x_width=5.5;
    y_width=2.75;
    set(gcf, 'PaperPosition', [0 0 x_width y_width]); %

    subplot(1,2,1)
    p1 = plot(rho_plot, 100*(power(1 + gveccollect(13, :), 12) - 1), '-k', 'LineWidth', 2);
    hold on ;
    p2 = plot(rho_plot, 100*(power(1 + gveccollect(14, :), 12) - 1), '--r', 'LineWidth', 2);
    xlabel('Discount rate, $\rho$', 'Interpreter', 'latex');
    ylabel('Growth rate, $g$', 'Interpreter', 'latex');
    xlim([0,5]);
    l1 = legend('Undirected', 'Directed', 'Interpreter', 'latex', 'Location', 'northeast');
    set(l1, 'box', 'off');

    subplot(1,2,2)
    p1 = plot(rho_plot, 100*(power(1 + markup_mean_collect(13, :), 1) - 1), '-k', 'LineWidth', 2);
    hold on ;
    p2 = plot(rho_plot, 100*(power(1 + markup_mean_collect(14, :), 1) - 1), '--r', 'LineWidth', 2);
    xlabel('Discount rate, $\rho$', 'Interpreter', 'latex');
    ylabel('Mean net markup', 'Interpreter', 'latex');
    xlim([0,5])

    saveas(gcf, "Output/Figures_Paper/ent_g_markup.eps", 'epsc');
    saveas(gcf, "Output/Figures_Paper/ent_g_markup.png");





    close all
    figure; 

    subplot(2,2,1)
    p1 = plot(rho_plot, 100*(power(1 + gveccollect(7, :), 12) - 1), '--r', 'LineWidth', 2);
    hold on 
    p2 = plot(rho_plot, 100*(power(1 + gveccollect(9, :), 12)-1), ':b', 'LineWidth', 2);
    p3 = plot(rho_plot, 100*(power(1 + gveccollect(8, :), 12) - 1), 'LineStyle', '-.', 'color', [0, 0.5, 0], 'LineWidth', 2);
    xlabel('Discount rate, $\rho$', 'Interpreter', 'latex');
    ylabel('Growth rate, $g$', 'Interpreter', 'latex');
    xlim([0,5]);
    m = models{7}(); 
    s1 = strcat("$\gamma = $", num2str(m.gamma)); 
    m = models{9}();
    s2 = strcat("$\kappa = $ ",num2str(m.kappa)); 
    m = models{8}();
    s3 = strcat("$\eta = $", num2str(m.eta(2)*12)); 
    l1 = legend([p1, p2, p3], s1, s2, s3, 'Interpreter', 'latex', 'Location', 'northeast');
    set(l1, 'box', 'off');


    subplot(2,2,2)
    p1 = plot(rho_plot, 100*(markup_mean_collect(7, :)), '--r', 'LineWidth', 2);
    hold on 
    p2 = plot(rho_plot, 100*(markup_mean_collect(9, :)), ':b', 'LineWidth', 2);
    p3 = plot(rho_plot, 100*(markup_mean_collect(8, :)), 'LineStyle', '-.', 'color', [0, 0.5, 0], 'LineWidth', 2);
    ylabel('Mean net markup', 'Interpreter', 'latex');
    xlabel('Discount rate, $\rho$', 'Interpreter', 'latex');
    xlim([0,5]);

    subplot(2,2,3)
    p1 = plot(rho_plot, 100*(power(1+gveccollect(6, :),12)-1), '--r', 'LineWidth', 2);
    hold on
    p2 = plot(rho_plot, 100*(power(1+gveccollect(1, :),12)-1), 'LineStyle', '-.', 'LineWidth', 2, 'color', [0, 0.5, 0]);
    xlabel('Discount rate, $\rho$', 'Interpreter', 'latex');
    ylabel('Growth rate, $g$', 'Interpreter', 'latex');
    xlim([0,5]);
    m = models{6}(); 
    s1 = strcat("$\varphi = $", num2str(m.EIS)); 
    m = models{1}();
    s2 = "Inelastic labor";
    l1 = legend([p1, p2], s1, s2, 'Interpreter', 'latex', 'Location', 'northeast');
    set(l1, 'box', 'off');

    subplot(2,2,4)
    p1 = plot(rho_plot, 100*(markup_mean_collect(6, :)), '--r', 'LineWidth', 2);
    hold on ;
    p2 = plot(rho_plot, 100*(markup_mean_collect(1, :)), 'LineStyle', '-.', 'color', [0, 0.5, 0], 'LineWidth', 2);
    ylabel('Mean net markup', 'Interpreter', 'latex');
    xlabel('Discount rate, $\rho$', 'Interpreter', 'latex');
    xlim([0,5]);

    saveas(gcf, "Output/Figures_Paper/robustness_main.png");
    saveas(gcf, "Output/Figures_Paper/robustness_main.eps", 'epsc');



    close all
    figure; 

    subplot(2,2,1)
    p1 = plot(rho_plot, 100*(power(1 + gveccollect(2, :), 12) - 1), '--r', 'LineWidth', 2);
    hold on ;
    p2 = plot(rho_plot, 100*(power(1 + gveccollect(10, :),12)-1), ':b',  'LineWidth', 2);
    p3 = plot(rho_plot, 100*(power(1 + gveccollect(11, :),12)-1), 'LineStyle', ...
            '-.', 'color', [0,0.5,0], 'LineWidth', 2);
    xlabel('Discount rate, $\rho$', 'Interpreter', 'latex');
    ylabel('Growth rate, $g$', 'Interpreter', 'latex');
    xlim([0,5]);
    m = models{2}(); 
    s1 = strcat("$\gamma = $ ", num2str(m.gamma)); 
    m = models{10}();
    s2 = strcat("$\kappa = $ ", num2str(m.kappa));
    m = models{11}();
    s3 = strcat("$\kappa = $    ", num2str(m.kappa));
    l1 = legend([p1,p2,p3], s1,s2,s3, 'Interpreter', 'latex', 'Location', 'northeast');
    set(l1, 'box', 'off');


    subplot(2,2,2)
    p1 = plot(rho_plot, 100*(markup_mean_collect(2, :)), '--r', 'LineWidth', 2);
    hold on ;
    p2 = plot(rho_plot, 100*(markup_mean_collect(10, :)), ':b', 'LineWidth', 2);
    p3 = plot(rho_plot, 100*(markup_mean_collect(11, :)), 'LineStyle', '-.', 'color', [0, 0.5, 0], 'LineWidth', 2);
    ylabel('Mean net markup', 'Interpreter', 'latex');
    xlabel('Discount rate, $\rho$', 'Interpreter', 'latex');
    xlim([0,5]);

    subplot(2,2,3)
    p1 = plot(rho_plot, 100*(power(1+gveccollect(3, :),12)-1), '--r', 'LineWidth', 2);
    hold on;
    p2 = plot(rho_plot, 100*(power(1+gveccollect(5, :),12)-1), 'LineStyle', ':', 'LineWidth', 2, 'color', 'b');
    p3 = plot(rho_plot, 100*(power(1+gveccollect(4, :),12)-1), 'LineStyle', '-.', 'LineWidth', 2, 'color', [0, 0.5, 0]);
    xlabel('Discount rate, $\rho$', 'Interpreter', 'latex');
    ylabel('Growth rate, $g$', 'Interpreter', 'latex');
    xlim([0,5]);
    m = models{3}(); 
    s1 = strcat("$\eta = $", num2str(m.eta(2)*12)); 
    m = models{5}();
    s2 = strcat("$\varphi = $", num2str(m.EIS)); 
    m = models{4}(); 
    s3 = strcat("$\rho = $", num2str(100*(power(1+m.rho,12)-1)), "\%");
    l1 = legend([p1, p2, p3], s1, s2, s3, 'Interpreter', 'latex', 'Location', 'northeast');
    set(l1, 'box', 'off');

    subplot(2,2,4)
    p1 = plot(rho_plot, 100*(markup_mean_collect(3, :)), '--r', 'LineWidth', 2);
    hold on ;
    p2 = plot(rho_plot, 100*(markup_mean_collect(5, :)), 'LineStyle', ':', 'color', 'b', 'LineWidth', 2);
    p3 = plot(rho_plot, 100*(markup_mean_collect(4, :)), 'LineStyle', '-.', 'color', [0, 0.5, 0], 'LineWidth', 2);
    ylabel('Mean net markup', 'Interpreter', 'latex');
    xlabel('Discount rate, $\rho$', 'Interpreter', 'latex');
    xlim([0,5]);

    saveas(gcf, "Output/Figures_Paper/robustness_IA.png");
    saveas(gcf, "Output/Figures_Paper/robustness_IA.eps", 'epsc');



    close all
    figure; 


    set(gcf, 'PaperUnits', 'inches');
    x_width=3.25;
    y_width=4.2;
    set(gcf, 'PaperPosition', [0 0 x_width y_width]); %


    subplot(2,1,1)
    p1 = plot(rho_plot, 100*(power(1+gveccollect(12, :), 12) - 1), ':b', 'LineWidth', 2);
    ylabel('Growth, $g$', 'Interpreter', 'latex');
    xlabel('Discount rate, $\rho$', 'Interpreter', 'latex');
    xlim([0,5]);

    subplot(2,1,2)
    p2 = plot(rho_plot, 100*markup_mean_collect(12, :), ':b', 'LineWidth', 2);
    ylabel('Mean net markup', 'Interpreter', 'latex');
    xlabel('Discount rate, $\rho$', 'Interpreter', 'latex');
    xlim([0,5]);

    saveas(gcf, "Output/Figures_Paper/markup_high.png");
    saveas(gcf, "Output/Figures_Paper/markup_high.eps", 'epsc');

end